### ISSUE TITLE
Formatting large numbers 

### ISSUE THREAD

**Issue by prastut** [buidl-labs/livepeer-pricing-tool#6]
Current Delegated Stake numbers are not easy to read

eg: 879835.8118972158 LPT

A easier version to read is 879,835.81 LPT

Recommended library to use: 
https://github.com/s-yadav/react-number-format#readme

**Comment by Saumay-Agrawal** [comment]
Your advice needed. 

Situation: 
* We get the raw delegated stake value in LPTU (1 LPT = 10^18 LPTU).
* Some orchestrators do have values like 5 LPTU (ie 5 * 10^18 LPT). Such orchestrators aren't visible in current UI as they are being excluded due to being unreachable, but they could get listed in the future. More context here: https://github.com/livepeer/Grant-Program/issues/5#issuecomment-611981903
* Hence I need to first decide whether to show the value in LPT or LPTU and then format it accordingly. The current method of handling this can be viewed at https://github.com/buidl-labs/livepeer-pricing-tool/blob/34ded3546a84ac35b98ac4f8e79ade93e1dffaf3/ui/src/components/OrchestratorTable.js#L79

NOTE: This was the cause behind the broken sorting of the Delegated Stake column. Pointing the row comparer to raw delegated stake values has fixed that issue. 

Ask:
What would be the optimum methodology for the Delegated Stake value conversion (breakpoint at which LPTU is converted into LPT, which right now is 10^12)? 
Formatting would just be a function of this issue.

**Comment by prastut** [comment]
Lack sufficient vantage to answer this. Need to understand the state of mind of the orchestrator to better answer this. 

Deprioritize for now. Put this on the call of things we need to discuss.
